#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/polyMesh/boundary
\rm -rf history

\rm -f constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -rf ../solid/VTK
\rm -f *.ps
\rm -f *.pdf
\rm -f *.vtk
\rm fort.90
\rm Case.run

cd ..
./removeSerialLinks fluid

cd solid
cleanCase
\rm -rf processor*
cd ..
cd fluid
