#!/bin/sh

# Source Foam bashrc
source ${HOME}/foam/foam-extend-4.0/etc/bashrc

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

# Build solid domain
runApplication -l log.blockMesh.solid blockMesh -case ../solid
runApplication -l log.setSet.solid setSet -case ../solid -batch ../solid/setBatch
runApplication -l log.setToZones.solid setsToZones -case ../solid -noFlipMap

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

cd ..

./makeSerialLinks fluid solid

cd fluid

runApplication $application &

# ----------------------------------------------------------------- end-of-file
